# Generated by Django 4.2.2 on 2023-06-13 07:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_id', models.CharField(max_length=223)),
                ('address', models.CharField(max_length=555)),
                ('check_in_time', models.CharField(max_length=123)),
                ('check_out_time', models.CharField(max_length=123)),
                ('kind', models.CharField(max_length=223)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=223)),
                ('phone', models.CharField(max_length=22)),
                ('postal_code', models.CharField(max_length=120)),
                ('star_rating', models.FloatField(default=0)),
                ('email', models.CharField(max_length=123)),
                ('semantic_version', models.CharField(max_length=1000)),
                ('is_closed', models.BooleanField(default=False)),
                ('metapolicy_extra_info', models.TextField()),
                ('star_certificate', models.CharField(max_length=123)),
                ('hotel_chain', models.CharField(max_length=223)),
                ('front_desk_time_start', models.CharField(max_length=123)),
                ('front_desk_time_end', models.CharField(max_length=123)),
                ('is_gender_specification_required', models.BooleanField(default=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
                ('payment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
                ('country_code', models.CharField(max_length=4)),
                ('region_iata', models.CharField(max_length=5)),
                ('region_id', models.IntegerField()),
                ('region_name', models.CharField(max_length=1234)),
                ('region_type', models.CharField(max_length=1234)),
                ('serp_filters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RoomGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
                ('name', models.CharField(max_length=1234)),
                ('room_amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=222), default=list, size=None)),
                ('room_group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2222)),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='AmenityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=2222)),
                ('amenities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.hotel')),
            ],
        ),
    ]
