# Generated by Django 4.2.2 on 2023-06-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='front_desk_time_end',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='front_desk_time_start',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_chain',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='images',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_gender_specification_required',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='metapolicy_extra_info',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region_iata',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region_id',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='semantic_version',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='star_certificate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='star_rating',
        ),
    ]
