# Generated by Django 4.2.2 on 2023-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_remove_hotel_country_code_remove_hotel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='sort_id',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
    ]
