# Generated by Django 4.2.2 on 2023-06-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_alter_hotel_sort_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policystruct',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.hotel'),
        ),
        migrations.AddField(
            model_name='roomgroups',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.hotel'),
        ),
    ]
