# Generated by Django 4.2.2 on 2023-06-13 11:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_policystruct_hotel_roomgroups_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='front_desk_time_end',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='front_desk_time_start',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_chain',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_gender_specification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='metapolicy_extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1250), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region_iata',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region_name',
            field=models.CharField(blank=True, max_length=1234, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region_type',
            field=models.CharField(blank=True, max_length=1234, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='semantic_version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_certificate',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='amenitygroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=2222, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionstruct',
            name='paragraphs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1250, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='descriptionstruct',
            name='title',
            field=models.CharField(blank=True, max_length=2222, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='kind',
            field=models.CharField(blank=True, max_length=223, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sort_id',
            field=models.CharField(max_length=223, null=True),
        ),
        migrations.AlterField(
            model_name='policystruct',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='roomgroups',
            name='name',
            field=models.CharField(blank=True, max_length=1234, null=True),
        ),
        migrations.AlterField(
            model_name='roomgroups',
            name='room_amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=222, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='roomgroups',
            name='room_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
