# Generated by Django 4.2.2 on 2023-06-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_hotel_country_code_hotel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star_certificate',
            field=models.CharField(blank=True, max_length=1234, null=True),
        ),
    ]
