# Generated by Django 4.2.2 on 2023-06-13 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_hotel_star_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.CharField(blank=True, max_length=1213, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.CharField(blank=True, max_length=1213, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(blank=True, max_length=1231, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='front_desk_time_end',
            field=models.CharField(blank=True, max_length=1123, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='front_desk_time_start',
            field=models.CharField(blank=True, max_length=1213, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_chain',
            field=models.CharField(blank=True, max_length=2123, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='kind',
            field=models.CharField(blank=True, max_length=2213, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.CharField(blank=True, max_length=1001, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.CharField(blank=True, max_length=1001, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=2222, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(blank=True, max_length=1220, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sort_id',
            field=models.CharField(max_length=2213, null=True),
        ),
        migrations.AlterField(
            model_name='roomgroups',
            name='room_amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2122, null=True), default=list, size=None),
        ),
    ]
