# Generated by Django 4.2.2 on 2023-06-14 10:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_hotel_check_in_time_alter_hotel_check_out_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('iata', models.CharField(blank=True, max_length=123, null=True)),
                ('country_name', models.CharField(blank=True, max_length=2222, null=True)),
                ('country_code', models.CharField(blank=True, max_length=223, null=True)),
                ('longitude', models.CharField(blank=True, max_length=333, null=True)),
                ('latitude', models.CharField(blank=True, max_length=333, null=True)),
                ('hotels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2122, null=True), default=list, size=None)),
                ('type', models.CharField(blank=True, max_length=2222, null=True)),
                ('name', models.CharField(blank=True, max_length=1234, null=True)),
            ],
        ),
    ]
